"""Test case ID mapping for all test cases."""
# Dictionary mapping test function names to test case IDs

TEST_CASE_MAPPING = {
    # Login Tests
    "test_login_page_loads": "TC_LOGIN_001",
    "test_admin_login_success": "TC_LOGIN_002",
    "test_dashboard_visible_after_admin_login": "TC_LOGIN_003",
    "test_login_with_trimmed_and_uppercase_email": "TC_LOGIN_004",
    "test_user_login_not_authorized": "TC_LOGIN_005",
    "test_dashboard_url_blocked_without_login": "TC_LOGIN_006",
    "test_login_page_elements": "TC_LOGIN_007",
    "test_login_with_different_credentials": "TC_LOGIN_008",
    "test_admin_login_flow": "TC_LOGIN_009",
    "test_user_login_flow_unauthorized": "TC_LOGIN_010",
    "test_login_with_whitespace_in_email": "TC_LOGIN_011",
    "test_login_with_uppercase_email": "TC_LOGIN_012",
    "test_direct_dashboard_access_blocked": "TC_LOGIN_013",
    "test_session_persistence": "TC_LOGIN_014",
    "test_multiple_login_attempts": "TC_LOGIN_015",
    
    # Invalid Login Tests
    "test_login_with_invalid_email": "TC_LOGIN_016",
    "test_login_with_invalid_password": "TC_LOGIN_017",
    "test_login_with_wrong_credentials": "TC_LOGIN_018",
    "test_login_with_empty_credentials": "TC_LOGIN_019",
    "test_login_with_sql_injection_attempt": "TC_LOGIN_020",
    "test_login_with_xss_attempt": "TC_LOGIN_021",
    "test_login_with_special_characters": "TC_LOGIN_022",
    "test_login_with_very_long_credentials": "TC_LOGIN_023",
    "test_multiple_failed_login_attempts": "TC_LOGIN_024",
    "test_login_error_messages": "TC_LOGIN_025",
    "test_login_case_sensitivity": "TC_LOGIN_026",
    "test_login_with_whitespace_only": "TC_LOGIN_027",
    "test_login_with_numeric_only_credentials": "TC_LOGIN_028",
    "test_login_page_stays_accessible_after_failed_login": "TC_LOGIN_029",
    
    # Unauthorized Access Tests
    "test_unauthorized_user_login_attempt": "TC_ACCESS_001",
    "test_unauthorized_user_direct_dashboard_access": "TC_ACCESS_002",
    "test_unauthorized_user_reports_access": "TC_ACCESS_003",
    "test_unauthorized_user_users_access": "TC_ACCESS_004",
    "test_unauthorized_user_branch_access": "TC_ACCESS_005",
    "test_unauthorized_user_tasks_access": "TC_ACCESS_006",
    "test_unauthorized_user_navigation_restrictions": "TC_ACCESS_007",
    "test_unauthorized_user_redirect_after_login": "TC_ACCESS_008",
    "test_unauthorized_user_session_handling": "TC_ACCESS_009",
    "test_unauthorized_vs_authorized_credentials": "TC_ACCESS_010",
    
    # Dashboard Tests
    "test_dashboard_visible_after_login": "TC_DASHBOARD_001",
    "test_dashboard_loads_after_login": "TC_DASHBOARD_002",
    "test_dashboard_elements_present": "TC_DASHBOARD_003",
    "test_dashboard_navigation": "TC_DASHBOARD_004",
    "test_dashboard_page_interactions": "TC_DASHBOARD_005",
    "test_dashboard_refresh": "TC_DASHBOARD_006",
    "test_dashboard_url_direct_access": "TC_DASHBOARD_007",
    "test_dashboard_access_with_both_users": "TC_DASHBOARD_008",
    "test_dashboard_content_loading": "TC_DASHBOARD_009",
    "test_dashboard_responsive_elements": "TC_DASHBOARD_010",
    "test_dashboard_key_metrics_displayed": "TC_DASHBOARD_011",
    "test_active_users_metric": "TC_DASHBOARD_012",
    "test_user_location_section_present": "TC_DASHBOARD_013",
    "test_search_users_functionality": "TC_DASHBOARD_014",
    "test_last_updated_display": "TC_DASHBOARD_015",
    "test_refresh_button_functionality": "TC_DASHBOARD_016",
    "test_areas_by_checked_in_users_section": "TC_DASHBOARD_017",
    "test_area_cards_displayed": "TC_DASHBOARD_018",
    "test_dashboard_interactive_elements": "TC_DASHBOARD_019",
    "test_dashboard_data_display": "TC_DASHBOARD_020",
    "test_dashboard_page_structure": "TC_DASHBOARD_021",
    
    # Reports Tests
    "test_reports_page_loads": "TC_REPORTS_001",
    "test_reports_page_elements_present": "TC_REPORTS_002",
    "test_reports_search_functionality": "TC_REPORTS_003",
    "test_reports_filter_functionality": "TC_REPORTS_004",
    "test_create_report_button_visible": "TC_REPORTS_005",
    "test_view_report_functionality": "TC_REPORTS_006",
    "test_reports_export_functionality": "TC_REPORTS_007",
    "test_reports_pagination": "TC_REPORTS_008",
    "test_reports_table_structure": "TC_REPORTS_009",
    "test_reports_page_refresh": "TC_REPORTS_010",
    "test_reports_direct_url_access": "TC_REPORTS_011",
    
    # Users Tests
    "test_users_page_loads": "TC_USERS_001",
    "test_users_page_elements_present": "TC_USERS_002",
    "test_users_search_functionality": "TC_USERS_003",
    "test_users_filter_by_role": "TC_USERS_004",
    "test_users_filter_by_status": "TC_USERS_005",
    "test_create_user_button_visible": "TC_USERS_006",
    "test_create_user_form_elements": "TC_USERS_007",
    "test_fill_user_form": "TC_USERS_008",
    "test_view_user_functionality": "TC_USERS_009",
    "test_edit_user_functionality": "TC_USERS_010",
    "test_users_table_structure": "TC_USERS_011",
    "test_users_pagination": "TC_USERS_012",
    "test_users_page_refresh": "TC_USERS_013",
    "test_users_direct_url_access": "TC_USERS_014",
    "test_cancel_user_form": "TC_USERS_015",
    
    # Branch Tests
    "test_branch_page_loads": "TC_BRANCH_001",
    "test_branch_page_elements_present": "TC_BRANCH_002",
    "test_branch_search_functionality": "TC_BRANCH_003",
    "test_branch_filter_by_location": "TC_BRANCH_004",
    "test_branch_filter_by_status": "TC_BRANCH_005",
    "test_create_branch_button_visible": "TC_BRANCH_006",
    "test_create_branch_form_elements": "TC_BRANCH_007",
    "test_fill_branch_form": "TC_BRANCH_008",
    "test_view_branch_functionality": "TC_BRANCH_009",
    "test_edit_branch_functionality": "TC_BRANCH_010",
    "test_branch_table_structure": "TC_BRANCH_011",
    "test_branch_pagination": "TC_BRANCH_012",
    "test_branch_page_refresh": "TC_BRANCH_013",
    "test_branch_direct_url_access": "TC_BRANCH_014",
    "test_cancel_branch_form": "TC_BRANCH_015",
    "test_branch_form_validation": "TC_BRANCH_016",
    
    # Tasks Tests
    "test_tasks_page_loads": "TC_TASKS_001",
    "test_tasks_page_elements_present": "TC_TASKS_002",
    "test_tasks_search_functionality": "TC_TASKS_003",
    "test_tasks_filter_by_status": "TC_TASKS_004",
    "test_tasks_filter_by_priority": "TC_TASKS_005",
    "test_create_task_button_visible": "TC_TASKS_006",
    "test_create_task_form_elements": "TC_TASKS_007",
    "test_fill_task_form": "TC_TASKS_008",
    "test_view_task_functionality": "TC_TASKS_009",
    "test_edit_task_functionality": "TC_TASKS_010",
    "test_tasks_table_structure": "TC_TASKS_011",
    "test_tasks_pagination": "TC_TASKS_012",
    "test_tasks_page_refresh": "TC_TASKS_013",
    "test_tasks_direct_url_access": "TC_TASKS_014",
    
    # Settings Tests
    "test_settings_page_loads": "TC_SETTINGS_001",
    "test_settings_page_elements_present": "TC_SETTINGS_002",
    "test_settings_tabs_switching": "TC_SETTINGS_003",
    "test_general_settings": "TC_SETTINGS_004",
    "test_profile_settings_update": "TC_SETTINGS_005",
    "test_security_settings_password_change": "TC_SETTINGS_006",
    "test_notifications_settings": "TC_SETTINGS_007",
    "test_settings_save_functionality": "TC_SETTINGS_008",
    "test_settings_cancel_functionality": "TC_SETTINGS_009",
    "test_settings_page_refresh": "TC_SETTINGS_010",
    "test_settings_direct_url_access": "TC_SETTINGS_011",
    "test_all_settings_tabs_accessible": "TC_SETTINGS_012",
    
    # Navigation Tests
    "test_navigation_menu_visible": "TC_NAV_001",
    "test_logout_functionality": "TC_NAV_002",
    "test_logout_and_login_again": "TC_NAV_003",
    "test_page_navigation_flow": "TC_NAV_004",
    "test_back_button_after_login": "TC_NAV_005",
    
    # Multiple Users Tests
    "test_multiple_user_login_access": "TC_MULTI_USER_001",
    "test_all_admin_users_access": "TC_MULTI_USER_002",
    "test_all_unauthorized_users_blocked": "TC_MULTI_USER_003",
    "test_user_switching_between_admin_accounts": "TC_MULTI_USER_004",
    "test_user_switching_between_unauthorized_accounts": "TC_MULTI_USER_005",
    "test_complete_user_list": "TC_MULTI_USER_006",
    
    # UI Elements Tests
    "test_page_title_present": "TC_UI_001",
    "test_page_url_structure": "TC_UI_002",
    "test_input_fields_functionality": "TC_UI_003",
    "test_button_clicks": "TC_UI_004",
    "test_page_responsiveness": "TC_UI_005",
    "test_page_load_performance": "TC_UI_006",
    "test_dashboard_content_visibility": "TC_UI_007",
    "test_form_validation": "TC_UI_008",
    "test_page_interactions_stability": "TC_UI_009",
    
    # End-to-End Tests
    "test_complete_user_journey_admin": "TC_E2E_001",
    "test_complete_user_journey_user": "TC_E2E_002",
    "test_multiple_user_sessions": "TC_E2E_003",
    "test_session_persistence_workflow": "TC_E2E_004",
    "test_error_recovery_workflow": "TC_E2E_005",
    "test_full_workflow_both_users": "TC_E2E_006",
    "test_full_application_navigation": "TC_E2E_007",
    "test_complete_user_management_workflow": "TC_E2E_008",
    "test_complete_branch_management_workflow": "TC_E2E_009",
    "test_complete_reports_workflow": "TC_E2E_010",
    "test_complete_settings_workflow": "TC_E2E_011",
    "test_multi_section_workflow": "TC_E2E_012",
    
    # Security Tests
    "test_sql_injection_in_login_email": "TC_SECURITY_001",
    "test_xss_attack_prevention": "TC_SECURITY_002",
    "test_password_visibility_toggle": "TC_SECURITY_003",
    "test_session_hijacking_prevention": "TC_SECURITY_004",
    "test_csrf_protection": "TC_SECURITY_005",
    "test_rate_limiting_on_failed_logins": "TC_SECURITY_006",
    "test_sensitive_data_in_url": "TC_SECURITY_007",
    "test_secure_cookies": "TC_SECURITY_008",
    "test_content_security_policy": "TC_SECURITY_009",
    "test_file_upload_security": "TC_SECURITY_010",
    "test_path_traversal_attempts": "TC_SECURITY_011",
    "test_open_redirect_vulnerability": "TC_SECURITY_012",
    
    # Data Validation Tests
    "test_email_format_validation": "TC_VALIDATION_001",
    "test_password_strength_validation": "TC_VALIDATION_002",
    "test_required_field_validation": "TC_VALIDATION_003",
    "test_max_length_validation": "TC_VALIDATION_004",
    "test_special_character_handling": "TC_VALIDATION_005",
    "test_numeric_validation": "TC_VALIDATION_006",
    "test_date_validation": "TC_VALIDATION_007",
    "test_phone_number_validation": "TC_VALIDATION_008",
    "test_whitespace_trimming": "TC_VALIDATION_009",
    "test_unicode_character_handling": "TC_VALIDATION_010",
    "test_case_sensitivity_validation": "TC_VALIDATION_011",
    
    # Performance Tests
    "test_page_load_time": "TC_PERFORMANCE_001",
    "test_login_response_time": "TC_PERFORMANCE_002",
    "test_dashboard_load_performance": "TC_PERFORMANCE_003",
    "test_image_load_performance": "TC_PERFORMANCE_004",
    "test_api_response_time": "TC_PERFORMANCE_005",
    "test_concurrent_page_loads": "TC_PERFORMANCE_006",
    "test_memory_usage": "TC_PERFORMANCE_007",
    "test_large_data_handling": "TC_PERFORMANCE_008",
    "test_caching_effectiveness": "TC_PERFORMANCE_009",
    
    # Accessibility Tests
    "test_keyboard_navigation": "TC_A11Y_001",
    "test_aria_labels": "TC_A11Y_002",
    "test_form_labels": "TC_A11Y_003",
    "test_color_contrast": "TC_A11Y_004",
    "test_screen_reader_compatibility": "TC_A11Y_005",
    "test_focus_indication": "TC_A11Y_006",
    "test_alt_text_for_images": "TC_A11Y_007",
    "test_skip_links": "TC_A11Y_008",
    "test_error_message_accessibility": "TC_A11Y_009",
    "test_responsive_design_accessibility": "TC_A11Y_010",
    "test_language_attribute": "TC_A11Y_011",
    
    # Edge Cases Tests
    "test_extremely_long_email": "TC_EDGE_001",
    "test_special_characters_in_email": "TC_EDGE_002",
    "test_unicode_in_inputs": "TC_EDGE_003",
    "test_empty_string_handling": "TC_EDGE_004",
    "test_only_whitespace_input": "TC_EDGE_005",
    "test_rapid_button_clicks": "TC_EDGE_006",
    "test_browser_back_button": "TC_EDGE_007",
    "test_page_refresh_during_action": "TC_EDGE_008",
    "test_multiple_tabs_sessions": "TC_EDGE_009",
    "test_network_timeout_handling": "TC_EDGE_010",
    "test_large_payload_handling": "TC_EDGE_011",
    "test_concurrent_user_actions": "TC_EDGE_012",
    "test_extreme_viewport_sizes": "TC_EDGE_013",
    "test_session_expiry_handling": "TC_EDGE_014",
    
    # Positive Cases Tests
    "test_successful_login_with_valid_credentials": "TC_POSITIVE_001",
    "test_successful_login_second_admin": "TC_POSITIVE_002",
    "test_dashboard_displays_correctly": "TC_POSITIVE_003",
    "test_navigation_to_all_sections": "TC_POSITIVE_004",
    "test_user_search_functionality": "TC_POSITIVE_005",
    "test_report_generation": "TC_POSITIVE_006",
    "test_form_submission": "TC_POSITIVE_007",
    "test_data_display": "TC_POSITIVE_008",
    "test_page_refresh_maintains_state": "TC_POSITIVE_009",
    "test_logout_functionality": "TC_POSITIVE_010",
    "test_multiple_successful_logins": "TC_POSITIVE_011",
    "test_smooth_user_experience": "TC_POSITIVE_012",
    "test_all_features_accessible": "TC_POSITIVE_013",
    
    # Search Comprehensive Tests
    "test_search_users_by_name": "TC_SEARCH_001",
    "test_search_users_by_email": "TC_SEARCH_002",
    "test_search_reports_by_name": "TC_SEARCH_003",
    "test_search_branches_by_name": "TC_SEARCH_004",
    "test_search_branches_by_code": "TC_SEARCH_005",
    "test_search_tasks_by_title": "TC_SEARCH_006",
    "test_search_case_insensitive": "TC_SEARCH_007",
    "test_search_with_special_characters": "TC_SEARCH_008",
    "test_search_clear_functionality": "TC_SEARCH_009",
    "test_search_empty_results": "TC_SEARCH_010",
    "test_search_partial_match": "TC_SEARCH_011",
    "test_search_with_whitespace": "TC_SEARCH_012",
    "test_search_real_time_updates": "TC_SEARCH_013",
    
    # Reports Comprehensive Tests
    "test_view_report_details": "TC_REPORTS_DETAIL_001",
    "test_filter_reports_by_date_range": "TC_REPORTS_DETAIL_002",
    "test_filter_reports_by_specific_date": "TC_REPORTS_DETAIL_003",
    "test_export_reports_pdf": "TC_REPORTS_DETAIL_004",
    "test_export_reports_excel": "TC_REPORTS_DETAIL_005",
    "test_pagination_next_page": "TC_REPORTS_DETAIL_006",
    "test_pagination_previous_page": "TC_REPORTS_DETAIL_007",
    "test_pagination_page_number_selection": "TC_REPORTS_DETAIL_008",
    "test_pagination_errors_on_invalid_page": "TC_REPORTS_DETAIL_009",
    "test_reports_table_sorting": "TC_REPORTS_DETAIL_010",
    "test_reports_table_column_visibility": "TC_REPORTS_DETAIL_011",
    "test_create_report_button_functionality": "TC_REPORTS_DETAIL_012",
    "test_edit_report_functionality": "TC_REPORTS_DETAIL_013",
    "test_delete_report_functionality": "TC_REPORTS_DETAIL_014",
    "test_delete_report_with_confirmation": "TC_REPORTS_DETAIL_015",
    
    # Users CRUD Comprehensive Tests
    "test_add_new_user_complete_form": "TC_USERS_CRUD_001",
    "test_add_user_minimum_required_fields": "TC_USERS_CRUD_002",
    "test_view_user_details": "TC_USERS_CRUD_003",
    "test_edit_existing_user": "TC_USERS_CRUD_004",
    "test_delete_newly_added_user": "TC_USERS_CRUD_005",
    "test_delete_user_with_confirmation": "TC_USERS_CRUD_006",
    "test_cancel_user_creation": "TC_USERS_CRUD_007",
    "test_user_form_validation_on_save": "TC_USERS_CRUD_008",
    "test_filter_users_after_adding": "TC_USERS_CRUD_009",
    "test_search_newly_added_user": "TC_USERS_CRUD_010",
    "test_view_multiple_users": "TC_USERS_CRUD_011",
    
    # Tasks Comprehensive Tests
    "test_add_new_task_complete_details": "TC_TASKS_CRUD_001",
    "test_add_task_minimum_fields": "TC_TASKS_CRUD_002",
    "test_view_task_details": "TC_TASKS_CRUD_003",
    "test_edit_task": "TC_TASKS_CRUD_004",
    "test_remove_delete_task": "TC_TASKS_CRUD_005",
    "test_carry_forward_task": "TC_TASKS_CRUD_006",
    "test_complete_task": "TC_TASKS_CRUD_007",
    "test_filter_tasks_by_status": "TC_TASKS_CRUD_008",
    "test_filter_tasks_by_priority": "TC_TASKS_CRUD_009",
    "test_search_tasks": "TC_TASKS_CRUD_010",
    "test_task_pagination": "TC_TASKS_CRUD_011",
    "test_add_task_and_verify_in_list": "TC_TASKS_CRUD_012",
    "test_task_due_date_validation": "TC_TASKS_CRUD_013",
    
    # Pagination Comprehensive Tests
    "test_reports_pagination_next_page": "TC_PAGINATION_001",
    "test_reports_pagination_previous_page": "TC_PAGINATION_002",
    "test_users_pagination_next_page": "TC_PAGINATION_003",
    "test_users_pagination_previous_page": "TC_PAGINATION_004",
    "test_branch_pagination_next_page": "TC_PAGINATION_005",
    "test_branch_pagination_previous_page": "TC_PAGINATION_006",
    "test_tasks_pagination_next_page": "TC_PAGINATION_007",
    "test_pagination_page_numbers": "TC_PAGINATION_008",
    "test_pagination_first_page_button": "TC_PAGINATION_009",
    "test_pagination_last_page_button": "TC_PAGINATION_010",
    "test_pagination_disabled_on_first_page": "TC_PAGINATION_011",
    "test_pagination_disabled_on_last_page": "TC_PAGINATION_012",
    "test_pagination_page_size_change": "TC_PAGINATION_013",
    "test_pagination_url_updates": "TC_PAGINATION_014",
    "test_pagination_with_search": "TC_PAGINATION_015",
    "test_pagination_with_filter": "TC_PAGINATION_016",
    
    # Tabs and Pages Comprehensive Tests
    "test_settings_general_tab": "TC_TABS_001",
    "test_settings_profile_tab": "TC_TABS_002",
    "test_settings_security_tab": "TC_TABS_003",
    "test_settings_notifications_tab": "TC_TABS_004",
    "test_switching_between_all_settings_tabs": "TC_TABS_005",
    "test_tab_content_persistence": "TC_TABS_006",
    "test_tab_keyboard_navigation": "TC_TABS_007",
    "test_dashboard_different_views": "TC_TABS_008",
    "test_page_refresh_maintains_active_tab": "TC_TABS_009",
    "test_direct_url_to_specific_tab": "TC_TABS_010",
    "test_tab_errors_handling": "TC_TABS_011",
    "test_tab_accessibility_labels": "TC_TABS_012",
    "test_multiple_pages_navigation": "TC_TABS_013",
    "test_breadcrumb_navigation": "TC_TABS_014",
    
    # Username/Password Normalization Tests
    "test_username_with_spaces_at_beginning_should_pass": "TC_NORMALIZATION_001",
    "test_username_with_spaces_at_end_should_pass": "TC_NORMALIZATION_002",
    "test_username_with_spaces_at_both_ends_should_pass": "TC_NORMALIZATION_003",
    "test_password_with_spaces_at_beginning_should_pass": "TC_NORMALIZATION_004",
    "test_password_with_spaces_at_end_should_pass": "TC_NORMALIZATION_005",
    "test_password_with_spaces_at_both_ends_should_pass": "TC_NORMALIZATION_006",
    "test_username_password_both_with_spaces_should_pass": "TC_NORMALIZATION_007",
    "test_username_uppercase_should_pass": "TC_NORMALIZATION_008",
    "test_username_mixed_case_should_pass": "TC_NORMALIZATION_009",
    "test_username_case_variations_should_all_pass": "TC_NORMALIZATION_010",
    "test_password_case_sensitive_uppercase_should_fail": "TC_NORMALIZATION_011",
    "test_password_case_sensitive_mixed_case_should_fail": "TC_NORMALIZATION_012",
    "test_username_uppercase_with_spaces_should_pass": "TC_NORMALIZATION_013",
    "test_password_with_spaces_but_wrong_case_should_fail": "TC_NORMALIZATION_014",
    "test_various_username_password_combinations": "TC_NORMALIZATION_015",
}

def get_test_case_id(test_name: str) -> str:
    """Get test case ID for a given test name."""
    # Try exact match first
    if test_name in TEST_CASE_MAPPING:
        return TEST_CASE_MAPPING[test_name]
    
    # Try to find partial match
    for key, value in TEST_CASE_MAPPING.items():
        if key in test_name or test_name in key:
            return value
    
    # Return generic ID if not found
    return "TC_GENERIC_001"

